name: PYTHON-PACKAGE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fix shallow clone warning for SonarCloud

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest

      - name: Lint with flake8
        run: flake8 --exit-zero

      - name: Run tests
        run: python -m pytest

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sources=.
            -Dsonar.python.version=3.13

      - name: Send Google Chat notification
        if: always()  # Always runs (success/failure)
        run: |
          STATUS="${{ job.status }}"
          curl -X POST -H 'Content-Type: application/json' \
          -d "{
            \"text\": \"📣 CI Pipeline **${STATUS}**\\n🔹 Repository: ${{ github.repository }}\\n🔹 Event: ${{ github.event_name }}\\n🔹 Triggered by: ${{ github.actor }}\\n🔹 Workflow: ${{ github.workflow }}\\n🔹 Commit: ${{ github.sha }}\\n🔗 [View Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})\"
          }" \
          "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"
